export const ENV = {
  SUPABASE: {
    SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL!,
    SUPABASE_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!,
    SUPABASE_SECRET_KEY: process.env.SUPABASE_SECRET_KEY!,
    SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY!,
    SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    STORAGE_BUCKET_NAME: process.env.NEXT_PUBLIC_STORAGE_BUCKET_NAME!,
    PROJECT_ID: process.env.NEXT_PUBLIC_PROJECT_ID!,
    STORAGE_VOICE_NOTE_BUCKET_NAME: process.env.NEXT_PUBLIC_STORAGE_VOICE_NOTE_BUCKET_NAME!
  },
  CLERK: {
    CLERK_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY!,
    CLERK_SECRET_KEY: process.env.CLERK_SECRET_KEY!,
    CLERK_WEBHOOKS_SECRET: process.env.CLERK_WEBHOOKS_SECRET!,
  },
};
