import type { Metadata } from "next";
import "./globals.css";
import QueryProvider from "@/providers/query-client-provider";
import { Toaster } from "sonner";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/providers/theme-provider";

import { Poppins } from "next/font/google";
import { SupabaseProvider } from "@/providers/supabase-provider";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppins.variable} font-sans antialiased bg-background`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ClerkProvider>
            <SupabaseProvider>
              <QueryProvider>
                {children}
                <Toaster theme="dark" position="bottom-right" duration={7000} />
              </QueryProvider>
            </SupabaseProvider>
          </ClerkProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
